# note: /workspace is a special directory in the docker image where all the files in this folder
# get placed on your behalf

steps:
# Go 1.6 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go16', '.']
  dir: go16
  id: go16-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/go16', '--config', '/workspace/go16.yaml', '-v']
  waitFor: ['go16-build']

# Go 1.8 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go18', '.']
  dir: go18
  id: go18-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/go18', '--config', '/workspace/go18.yaml', '-v']
  waitFor: ['go18-build']

# Go 1.9 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go19', '.']
  dir: go19
  id: go19-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/go19', '--config', '/workspace/go19.yaml', '-v']
  waitFor: ['go19-build']

# Go 1.10 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go110', '.']
  dir: go110
  id: go110-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/go110', '--config', '/workspace/go110.yaml', '-v']
  waitFor: ['go110-build']

# Go 1.11 build
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/go111', '.']
  dir: go111
  id: go111-build
  waitFor: ['-']
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', 'gcr.io/$PROJECT_ID/go111', '--config', '/workspace/go111.yaml', '-v']
  waitFor: ['go111-build']

images:
- gcr.io/$PROJECT_ID/go16
- gcr.io/$PROJECT_ID/go18
- gcr.io/$PROJECT_ID/go19
- gcr.io/$PROJECT_ID/go110
- gcr.io/$PROJECT_ID/go111